In [1]:
import numpy as np
import pandas as pd

In [2]:
trails = pd.read_csv("MaineScrape.csv", encoding = 'mac_roman' )

trails.shape

trails.head()

trails.dtypes

Unnamed: 0          int64
Trail_Name         object
Rank                int64
Difficulty         object
Distance_Miles    float64
Elevation_Feet      int64
Route_Type         object
Description        object
Latitude          float64
Longitude         float64
dtype: object

In [3]:
sum(trails.isnull().values)

#No missing values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
from sklearn import preprocessing

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import EllipticEnvelope
from sklearn.preprocessing import OneHotEncoder
from scipy import stats

In [6]:
ntrails = trails.iloc[:,3:7]

ntrailsonehot = trails.loc[:, ['Difficulty', 'Route_Type']]

ntrailsonehot.head()

Difficulty  Route_Type
0       Hard        Loop
1   Moderate  Out & Back
2   Moderate        Loop
3   Moderate        Loop
4       Hard        Loop

In [7]:
encode = preprocessing.OneHotEncoder()

# 2. Fit the encoder
encode.fit(ntrailsonehot)

# 3. Transform to binary columns
onehotlabels = encode.transform(ntrailsonehot).toarray()
onehotlabels.shape
onehotlabels


array([[0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       ...,
       [0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.]])

In [8]:
newcols = ['Cat1a', 'Cat1b', 'Cat1c', 'Cat2a', 'Cat2b', 'Cat2c']
catvardf = pd.DataFrame(onehotlabels, columns = newcols)

catvardf.shape

(1013, 6)

In [11]:
other_trails = trails.loc[:, ['Distance_Miles', 'Elevation_Feet']]

X = pd.concat((other_trails, catvardf), axis = 1)
X.shape

(1013, 8)

In [12]:
from sklearn.covariance import EllipticEnvelope
outlier_frac = 0.02

ell = EllipticEnvelope(contamination = outlier_frac)
ell.fit(X)

C:\Users\Jordan\Anaconda3\lib\site-packages\sklearn\covariance\robust_covariance.py:646: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "


EllipticEnvelope(assume_centered=False, contamination=0.02, random_state=None,
         store_precision=True, support_fraction=None)

In [13]:
#Checking for the number of outliers

pred = ell.predict(X)
print(sum(pred == -1) ) # Outlier points are predicted as -1
stats.itemfreq(pred)



21


C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  """


array([[ -1,  21],
       [  1, 992]], dtype=int64)

In [14]:
keep = pred == 1

Xkeep = X[keep]

print(Xkeep.shape)
Xkeep.head()

(992, 8)


Distance_Miles  Elevation_Feet  Cat1a  Cat1b  Cat1c  Cat2a  Cat2b  Cat2c
0             1.4             488    0.0    1.0    0.0    1.0    0.0    0.0
1             4.0            1118    0.0    0.0    1.0    0.0    1.0    0.0
2             3.4              95    0.0    0.0    1.0    1.0    0.0    0.0
3             3.1             597    0.0    0.0    1.0    1.0    0.0    0.0
4             2.1            1049    0.0    1.0    0.0    1.0    0.0    0.0

In [15]:
scaler = StandardScaler()

ready_to_clusterstd = scaler.fit_transform(Xkeep)

C:\Users\Jordan\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Jordan\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [16]:
from sklearn.decomposition import PCA

pca = PCA(0.90)
pca.fit(ready_to_clusterstd)

pca.n_components_

5

In [17]:
pca_components = pca.transform(ready_to_clusterstd)
pca_components.shape

(992, 5)

In [18]:
Xkeep["index"] = Xkeep.index
Xkeep2 = Xkeep.reset_index()
Xkeep2.head()

C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


level_0  Distance_Miles  Elevation_Feet  Cat1a  Cat1b  Cat1c  Cat2a  Cat2b  \
0        0             1.4             488    0.0    1.0    0.0    1.0    0.0   
1        1             4.0            1118    0.0    0.0    1.0    0.0    1.0   
2        2             3.4              95    0.0    0.0    1.0    1.0    0.0   
3        3             3.1             597    0.0    0.0    1.0    1.0    0.0   
4        4             2.1            1049    0.0    1.0    0.0    1.0    0.0   

   Cat2c  index  
0    0.0      0  
1    0.0      1  
2    0.0      2  
3    0.0      3  
4    0.0      4

In [19]:
cols = []
for i in range (1, 6):
    cols.append("PC" + str(i))

print(cols)

PCdf = pd.DataFrame(pca_components, columns = cols, index  =  Xkeep.index)
PCdf.head()

['PC1', 'PC2', 'PC3', 'PC4', 'PC5']


PC1       PC2       PC3       PC4       PC5
0  0.421829  1.685960  1.690911 -0.912417 -2.431638
1  1.709415 -0.981107 -1.136659 -0.353078  0.197947
2 -0.217829  1.343543 -1.417123 -0.269028  0.080668
3  0.067842  1.439754 -1.288501 -0.357195  0.046577
4  0.878991  1.851493  1.917381 -0.928493 -2.218600

In [20]:

labels = []
for i in range(5,13):
    kmeans = KMeans(n_clusters= i)
    kmeans = kmeans.fit(PCdf)
    labelPCdf = kmeans.labels_
    labels.append(labelPCdf)
    centroids = kmeans.cluster_centers_
    centroids[:, 0]
    print(stats.itemfreq(labelPCdf))
   


C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and 

[[  0 464]
 [  1 196]
 [  2  85]
 [  3 219]
 [  4  28]]
[[  0  85]
 [  1 285]
 [  2 196]
 [  3 219]
 [  4 179]
 [  5  28]]
[[  0 216]
 [  1 284]
 [  2 180]
 [  3  84]
 [  4 175]
 [  5  28]
 [  6  25]]
[[  0 216]
 [  1 284]
 [  2  43]
 [  3 180]
 [  4 175]
 [  5  41]
 [  6  28]
 [  7  25]]
[[  0 284]
 [  1 110]
 [  2  41]
 [  3 217]
 [  4 175]
 [  5  28]
 [  6  43]
 [  7  16]
 [  8  78]]
[[  0 160]
 [  1 284]
 [  2  15]
 [  3 175]
 [  4 109]
 [  5  41]
 [  6  28]
 [  7  58]
 [  8  79]
 [  9  43]]
[[  0 160]
 [  1 284]
 [  2  18]
 [  3 109]
 [  4 175]
 [  5  28]
 [  6  23]
 [  7  15]
 [  8  43]
 [  9  79]
 [ 10  58]]
[[  0 284]
 [  1 165]
 [  2  79]
 [  3 157]
 [  4  43]
 [  5  27]
 [  6  29]
 [  7  10]
 [  8  53]
 [  9 109]
 [ 10  13]
 [ 11  23]]


C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.


In [21]:
print(labels[1])

[0 2 3 3 0 0 4 3 0 1 3 3 0 2 3 3 1 2 2 0 0 3 3 4 3 2 3 3 3 1 4 3 4 3 0 2 0
 3 3 1 3 2 0 4 1 0 3 2 1 0 0 1 2 2 2 4 1 3 4 2 0 0 2 3 2 1 2 0 0 0 2 0 1 2
 2 3 3 3 3 3 0 2 1 3 0 4 0 3 3 3 1 2 1 2 3 1 2 2 4 0 0 2 3 2 3 3 5 0 2 4 4
 0 4 3 4 0 0 2 2 4 0 3 1 2 3 1 4 1 1 2 0 4 4 3 3 1 2 3 1 0 2 4 1 3 4 2 0 3
 2 2 3 1 0 2 2 1 4 3 3 3 2 3 1 2 2 3 4 3 1 0 3 3 1 2 0 3 4 4 1 4 3 3 3 0 3
 0 0 3 2 3 2 2 3 1 3 2 1 0 2 2 2 3 0 1 4 4 1 1 3 0 4 1 0 2 4 0 4 4 1 1 2 1
 3 3 3 2 2 1 3 3 2 2 2 2 1 4 3 2 4 2 3 3 2 1 2 0 0 1 2 2 2 1 1 3 2 4 4 3 2
 0 1 5 3 1 3 3 3 0 1 3 1 3 2 1 2 4 3 0 3 1 3 3 0 3 1 4 2 3 2 0 2 2 4 2 1 2
 1 0 1 4 1 1 1 3 0 5 1 2 3 3 1 2 5 2 2 2 3 1 1 1 4 4 4 1 2 1 2 1 2 4 4 2 0
 0 3 0 4 1 1 4 3 1 3 4 0 2 3 2 1 3 0 3 1 2 1 1 2 3 2 4 4 1 1 2 1 3 1 2 1 2
 2 4 2 2 3 2 2 1 3 1 4 3 3 3 3 2 2 1 3 2 4 2 4 2 3 2 1 3 2 5 1 1 1 1 4 3 1
 1 3 3 1 4 1 3 3 2 2 3 0 1 3 2 2 2 4 2 4 3 1 0 3 3 5 1 1 4 3 5 4 4 1 3 4 2
 1 4 2 3 1 1 3 0 0 4 5 4 1 2 2 3 3 1 1 0 3 0 2 1 0 2 3 3 3 3 4 4 1 2 3 1 4
 5 2 2 3 1 1 4 2 0 1 1 3 

In [22]:
#Let's go with 6 cluster groups
whole_cluster = labels[1]
whole_cluster.view()

PCdf["Cluster_number"] = whole_cluster
print(PCdf.head())
PCdf["Cluster_number"].value_counts()

        PC1       PC2       PC3       PC4       PC5  Cluster_number
0  0.421829  1.685960  1.690911 -0.912417 -2.431638               0
1  1.709415 -0.981107 -1.136659 -0.353078  0.197947               2
2 -0.217829  1.343543 -1.417123 -0.269028  0.080668               3
3  0.067842  1.439754 -1.288501 -0.357195  0.046577               3
4  0.878991  1.851493  1.917381 -0.928493 -2.218600               0


1    285
3    219
2    196
4    179
0     85
5     28
Name: Cluster_number, dtype: int64

In [23]:
completetrails = pd.concat([trails, PCdf], axis = 1)
completetrails.tail()

Unnamed: 0                                         Trail_Name  Rank  \
1008        1009                         Corinna Boardwalk [CLOSED]  1009   
1009        1010                   Bond Mountain [PRIVATE PROPERTY]  1010   
1010        1011            Porcupine and Notch Trail Loop [CLOSED]  1011   
1011        1012  Shell Pond Loop from Evergreen Valley Road [PR...  1012   
1012        1013                                Laughing Lion Trail  1013   

     Difficulty  Distance_Miles  Elevation_Feet  Route_Type  \
1008       Easy             0.6               6        Loop   
1009   Moderate             1.7             364  Out & Back   
1010   Moderate             3.6             275        Loop   
1011       Easy             3.7             232        Loop   
1012       Easy             1.7            1148  Out & Back   

                                            Description  Latitude  Longitude  \
1008  Corinna Boardwalk [CLOSED] is a 0.6 mile moder...  44.92228  -69.25973   
1009  Bond Mountain [PRIVATE PROPERTY] is a 1.7 mile...  43.62735  -70.89608   
1010  Porcupine and Notch Trail Loop [CLOSED] is a 3...  43.21542  -70.68492   
1011  Shell Pond Loop from Evergreen Valley Road is ...  44.24252  -70.96068   
1012  Laughing Lion Trail is a 1.7 mile moderately t...  44.29391  -70.99949   

           PC1       PC2       PC3       PC4       PC5  Cluster_number  
1008 -2.105159  0.390970  0.519763 -0.033098 -0.237612             1.0  
1009  0.913908 -1.279755 -1.549657 -0.439725 -0.418093             2.0  
1010 -0.074423  1.395277 -1.346425 -0.276145  0.143055             3.0  
1011 -1.545579  0.615573  0.836192  0.184868  0.531807             1.0  
1012 -0.034112 -1.878868  0.876356 -0.092561  0.010128             4.0

In [27]:
completetrails = completetrails.drop(['Unnamed: 0'], axis = 1)

In [62]:
completetrails.head()

completetrails["State"] = "Maine"
ncompletetrails = completetrails.loc[:,['Trail_Name','Rank','Difficulty','Distance_Miles','Elevation_Feet','Route_Type',
                                     'Description','Cluster_number', 'State','Latitude','Longitude']]


ncompletetrails

Trail_Name  Rank Difficulty  \
0                                The Beehive Loop Trail     1       Hard   
1                            Cadillac North Ridge Trail     2   Moderate   
2                           Jordan Pond Full Loop Trail     3   Moderate   
3            Ocean Path and Gorham Mountain Loop Trail      4   Moderate   
4     Precipice, Orange and Black and Champlain Nort...     5       Hard   
5              Cadillac Mountain South Ridge Trail Loop     6       Hard   
6      Ocean Path Trail: Thunder Hole and Monument Cove     7       Easy   
7                       Great Head Trail (Short Option)     8   Moderate   
8                             Tumbledown Mountain Trail     9       Hard   
9                            Cadillac Summit Loop Trail    10       Easy   
10                     Mount Agamenticus via Ring Trail    11   Moderate   
11           South Bubble Mountain and Jordan Pond Loop    12   Moderate   
12    Acadia Mountain and St. Sauveur Mountain Trail...    13       Hard   
13                                      Gorham Mountain    14   Moderate   
14       Bubbles Trail to Conners Nubble and Eagle Lake    15   Moderate   
15                          Burnt Meadow Mountain Trail    16   Moderate   
16                                    Ship Harbor Trail    17       Easy   
17          Pleasant Mountain via Southwest Ridge Trail    18   Moderate   
18                         Hunt and Helon Taylor Trail     19       Hard   
19                             Penobscot Mountain Trail    20   Moderate   
20                                  Katahdin Loop Trail    21       Hard   
21                           Dorr Mountain Ladder Trail    22       Hard   
22                         Great Head Trail (Full Loop)    23   Moderate   
23                            Beech Mountain Loop Trail    24   Moderate   
24                                     Bar Island Trail    25       Easy   
25          Scenic Trail Cut-off and Maiden Cliff Trail    26   Moderate   
26                    Ledges Trail to Pleasant Mountain    27   Moderate   
27                                       The Bowl Trail    28   Moderate   
28                                     Gulf Hagas Trail    29   Moderate   
29                          Douglas Mountain Loop Trail    30   Moderate   
...                                                 ...   ...        ...   
983   Rufus Jones Trail, Partridge Trail, and Esker ...   984       Easy   
984           Randall Mountain Trail [PRIVATE PROPERTY]   985   Moderate   
985                            Jerusalem Mountain Trail   986       Easy   
986                    Camp Ketcha and Libby River Loop   987       Easy   
987                         Geology and Rocky End Loop    988       Easy   
988                                 Little Nature Loop    989       Easy   
989                                Horseman Point Trail   990       Easy   
990                Black Head Trail to Fern Glenn Trail   991   Moderate   
991                                      Ice Pond Trail   992       Easy   
992              Peterís Brook Trail [PRIVATE PROPERTY]   993   Moderate   
993               Scenic Shore Trail [PRIVATE PROPERTY]   994       Hard   
994                        Gibson Preserve Nature Trail   995       Easy   
995                         Johnson Field Preserve Loop   996       Easy   
996                                      Long Cove Path   997       Easy   
997                      Horseshoe and Rocky End Trail    998       Easy   
998                       Maryís Woods at Cutting Creek   999       Easy   
999                             John Segur Nature Trail  1000   Moderate   
1000                                        Alder Trail  1001   Moderate   
1001                                  Mahoosuc Traverse  1002       Hard   
1002              Migis Lodge Trails [PRIVATE PROPERTY]  1003       Easy   
1003           North Basin from Chimney Pond Campground  1004   Moderate   
1004             

In [60]:
nhtrails = pd.read_csv("FinalClusterTrail.csv")

nhtrails['State'] = "New Hampshire"


nnhtrails = nhtrails.loc[:,['Trail_Name','Rank','Difficulty','Distance_Miles','Elevation_Feet','Route_Type',
                                     'Description','Cluster_number', 'State','Latitude','Longitude']]
nnhtrails

Trail_Name  Rank Difficulty  \
0        Mount Lafayette and Franconia Ridge Trail Loop     1       Hard   
1                           Welch and Dickey Loop Trail     2       Hard   
2                                   Mount Willard Trail     3   Moderate   
3     Mount Monadnock via White Dot and White Cross ...     4       Hard   
4                      Mount Major and Brook Trail Loop     5   Moderate   
5            Tuckerman Ravine Trail to Mount Washington     6       Hard   
6                                   Lonesome Lake Trail     7   Moderate   
7                  Mount Moosilauke and South Peak Loop     8       Hard   
8                                  Champney Falls Trail     9   Moderate   
9           Arethusa Falls and Frankenstein Cliff Trail    10       Hard   
10                                The Flume Gorge Trail    11       Easy   
11               Mount Pemigewasset Trail (Indian Head)    12   Moderate   
12                                 Mount Tecumseh Trail    13   Moderate   
13             Little Haystack via Falling Waters Trail    14       Hard   
14                                        Diana's Baths    15       Easy   
15                                   Boulder Loop Trail    16   Moderate   
16                                   Artist Bluff Trail    17   Moderate   
17    Arethusa Falls Via Bemis Brook and Arethusa Fa...    18   Moderate   
18    Mt. Washington via Jewell Trail, Gulfside Trai...    19       Hard   
19                            Mount Chocorua Loop Trail    20       Hard   
20                            Mount Cardigan Loop Trail    21   Moderate   
21                            South Moat Mountain Trail    22       Hard   
22               Champney Brook Trail to Mount Chocorua    23   Moderate   
23           Mount Osceola Trail to Greeley Ponds Trail    24       Hard   
24           Mount Osceola Trail to Greeley Ponds Trail    25       Hard   
25                                  Basin Cascade Trail    26   Moderate   
26                                Mount Kearsarge North    27       Hard   
27                          Presidential Traverse Trail    28       Hard   
28                                      Black Cap Trail    29   Moderate   
29                                      Sabbaday Falls     30       Easy   
...                                                 ...   ...        ...   
1166                          Old Greenfield Road Trail  1167       Easy   
1167                Lake Francis State Park River Trail  1168       Easy   
1168                                   Waldo's Way Loop  1169   Moderate   
1169  Austin Brook, Gentian Pond, Dream Lake and Pea...  1170       Hard   
1170                     Reel Brook Trail to Mount Wolf  1171       Hard   
1171       Appalachian Trail to Route 25 and Mount Cube  1172   Moderate   
1172                  Birch Ridge Community Forest Loop  1173       Easy   
1173                                  Lamson Farm Trail  1174       Easy   
1174                                    Bracken's Trail  1175       Easy   
1175    Ragged Mountain from Andover [PRIVATE PROPERTY]  1176   Moderate   
1176              Betty's Hill and Bill's Cutoff Trail   1177       Easy   
1177  Middle Mountain via Peabody Brooke, Gates Broo...  1178       Hard   
1178  Nineteen Mile Brook, Carter Notch, Imp and Wil...  1179       Hard   
1179                              Sullivan Nature Trail  1180       Easy   
1180                         Mount Elinor to BRCF Cabin  1181       Easy   
1181                                  Eagle Scout Trail  1182       Easy   
1182                   Pine Link Trail to Mount Madison  1183       Hard   
1183                                       Goodhue Hill  1184   Moderate   
1184                           Anderson Lane Trail Loop  1185       Easy   
1185                                          Jims Road  1186       Easy   
1186                                          Oak Trail  1187       Easy   
1187             

In [61]:
alltrails = pd.concat([ncompletetrails, nnhtrails])

print(alltrails.shape)
alltrails

(2209, 11)


Trail_Name  Rank Difficulty  \
0                                The Beehive Loop Trail     1       Hard   
1                            Cadillac North Ridge Trail     2   Moderate   
2                           Jordan Pond Full Loop Trail     3   Moderate   
3            Ocean Path and Gorham Mountain Loop Trail      4   Moderate   
4     Precipice, Orange and Black and Champlain Nort...     5       Hard   
5              Cadillac Mountain South Ridge Trail Loop     6       Hard   
6      Ocean Path Trail: Thunder Hole and Monument Cove     7       Easy   
7                       Great Head Trail (Short Option)     8   Moderate   
8                             Tumbledown Mountain Trail     9       Hard   
9                            Cadillac Summit Loop Trail    10       Easy   
10                     Mount Agamenticus via Ring Trail    11   Moderate   
11           South Bubble Mountain and Jordan Pond Loop    12   Moderate   
12    Acadia Mountain and St. Sauveur Mountain Trail...    13       Hard   
13                                      Gorham Mountain    14   Moderate   
14       Bubbles Trail to Conners Nubble and Eagle Lake    15   Moderate   
15                          Burnt Meadow Mountain Trail    16   Moderate   
16                                    Ship Harbor Trail    17       Easy   
17          Pleasant Mountain via Southwest Ridge Trail    18   Moderate   
18                         Hunt and Helon Taylor Trail     19       Hard   
19                             Penobscot Mountain Trail    20   Moderate   
20                                  Katahdin Loop Trail    21       Hard   
21                           Dorr Mountain Ladder Trail    22       Hard   
22                         Great Head Trail (Full Loop)    23   Moderate   
23                            Beech Mountain Loop Trail    24   Moderate   
24                                     Bar Island Trail    25       Easy   
25          Scenic Trail Cut-off and Maiden Cliff Trail    26   Moderate   
26                    Ledges Trail to Pleasant Mountain    27   Moderate   
27                                       The Bowl Trail    28   Moderate   
28                                     Gulf Hagas Trail    29   Moderate   
29                          Douglas Mountain Loop Trail    30   Moderate   
...                                                 ...   ...        ...   
1166                          Old Greenfield Road Trail  1167       Easy   
1167                Lake Francis State Park River Trail  1168       Easy   
1168                                   Waldo's Way Loop  1169   Moderate   
1169  Austin Brook, Gentian Pond, Dream Lake and Pea...  1170       Hard   
1170                     Reel Brook Trail to Mount Wolf  1171       Hard   
1171       Appalachian Trail to Route 25 and Mount Cube  1172   Moderate   
1172                  Birch Ridge Community Forest Loop  1173       Easy   
1173                                  Lamson Farm Trail  1174       Easy   
1174                                    Bracken's Trail  1175       Easy   
1175    Ragged Mountain from Andover [PRIVATE PROPERTY]  1176   Moderate   
1176              Betty's Hill and Bill's Cutoff Trail   1177       Easy   
1177  Middle Mountain via Peabody Brooke, Gates Broo...  1178       Hard   
1178  Nineteen Mile Brook, Carter Notch, Imp and Wil...  1179       Hard   
1179                              Sullivan Nature Trail  1180       Easy   
1180                         Mount Elinor to BRCF Cabin  1181       Easy   
1181                                  Eagle Scout Trail  1182       Easy   
1182                   Pine Link Trail to Mount Madison  1183       Hard   
1183                                       Goodhue Hill  1184   Moderate   
1184                           Anderson Lane Trail Loop  1185       Easy   
1185                                          Jims Road  1186       Easy   
1186                                          Oak Trail  1187       Easy   
1187             

In [73]:
alltrails.to_csv("NHMaineTrails.csv")

In [77]:
alltrails = pd.read_csv("NHMaineTrails.csv")

alltrails.shape

(2209, 11)

In [78]:
nalltrails = alltrails.loc[:,['Rank','Difficulty','Distance_Miles','Elevation_Feet','Route_Type']]
print(nalltrails.shape)
nalltrails

(2209, 5)


Rank Difficulty  Distance_Miles  Elevation_Feet      Route_Type
0        1       Hard             1.4             488            Loop
1        2   Moderate             4.0            1118      Out & Back
2        3   Moderate             3.4              95            Loop
3        4   Moderate             3.1             597            Loop
4        5       Hard             2.1            1049            Loop
5        6       Hard             7.5            2247            Loop
6        7       Easy             4.5             374      Out & Back
7        8   Moderate             1.6             301            Loop
8        9       Hard             5.3            1952            Loop
9       10       Easy             0.3              45            Loop
10      11   Moderate             1.7             334            Loop
11      12   Moderate             1.4             492            Loop
12      13       Hard             3.5            1167            Loop
13      14   Moderate             1.6             429      Out & Back
14      15   Moderate             4.4            1551            Loop
15      16   Moderate             3.6            1391            Loop
16      17       Easy             1.3              65            Loop
17      18   Moderate             5.4            1984      Out & Back
18      19       Hard            17.0            8021            Loop
19      20   Moderate             2.9             974      Out & Back
20      21       Hard             9.1            3894            Loop
21      22       Hard             2.7            1131            Loop
22      23   Moderate             1.8             265            Loop
23      24   Moderate             1.2             347            Loop
24      25       Easy             1.8             170      Out & Back
25      26   Moderate             1.7             731            Loop
26      27   Moderate             3.3            1512      Out & Back
27      28   Moderate             1.3             449            Loop
28      29   Moderate             7.5             977            Loop
29      30   Moderate             1.8             475            Loop
...    ...        ...             ...             ...             ...
2179  1167       Easy             1.4             160      Out & Back
2180  1168       Easy             1.4              72      Out & Back
2181  1169   Moderate             1.7             324            Loop
2182  1170       Hard            10.7            2188            Loop
2183  1171       Hard             8.8            2247      Out & Back
2184  1172   Moderate            13.3            4081  Point to Point
2185  1173       Easy             2.6             272            Loop
2186  1174       Easy             3.1             311            Loop
2187  1175       Easy             3.2             187      Out & Back
2188  1176   Moderate             6.3            1689            Loop
2189  1177       Easy             0.6             144            Loop
2190  1178       Hard             7.8            1509            Loop
2191  1179       Hard            27.5            6341            Loop
2192  1180       Easy             0.5               9            Loop
2193  1181       Easy             2.7             728  Point to Point
2194  1182       Easy             0.6              13            Loop
2195  1183       Hard             9.1            3848      Out & Back
2196  1184   Moderate             2.0             469      Out & Back
2197  1185       Easy             2.2             114            Loop
2198  1186       Easy             1.9             170      Out & Back
2199  1187       Easy             2.2             147      Out & Back
2200  1188       Easy             0.4              88      Out & Back
2201  1189       Easy             1.1               3      Out & Back
2202  1190   Moderate             3.4             419      Out & Back
2203  1191   Moderate             3.8            1364            Loop
2204  1192      

In [79]:
nalltrailsonehot = nalltrails.loc[:, ['Difficulty', 'Route_Type']]
nalltrailsonehot

Difficulty      Route_Type
0          Hard            Loop
1      Moderate      Out & Back
2      Moderate            Loop
3      Moderate            Loop
4          Hard            Loop
5          Hard            Loop
6          Easy      Out & Back
7      Moderate            Loop
8          Hard            Loop
9          Easy            Loop
10     Moderate            Loop
11     Moderate            Loop
12         Hard            Loop
13     Moderate      Out & Back
14     Moderate            Loop
15     Moderate            Loop
16         Easy            Loop
17     Moderate      Out & Back
18         Hard            Loop
19     Moderate      Out & Back
20         Hard            Loop
21         Hard            Loop
22     Moderate            Loop
23     Moderate            Loop
24         Easy      Out & Back
25     Moderate            Loop
26     Moderate      Out & Back
27     Moderate            Loop
28     Moderate            Loop
29     Moderate            Loop
...         ...             ...
2179       Easy      Out & Back
2180       Easy      Out & Back
2181   Moderate            Loop
2182       Hard            Loop
2183       Hard      Out & Back
2184   Moderate  Point to Point
2185       Easy            Loop
2186       Easy            Loop
2187       Easy      Out & Back
2188   Moderate            Loop
2189       Easy            Loop
2190       Hard            Loop
2191       Hard            Loop
2192       Easy            Loop
2193       Easy  Point to Point
2194       Easy            Loop
2195       Hard      Out & Back
2196   Moderate      Out & Back
2197       Easy            Loop
2198       Easy      Out & Back
2199       Easy      Out & Back
2200       Easy      Out & Back
2201       Easy      Out & Back
2202   Moderate      Out & Back
2203   Moderate            Loop
2204       Easy            Loop
2205   Moderate            Loop
2206       Hard      Out & Back
2207       Hard            Loop
2208       Easy            Loop

[2209 rows x 2 columns]

In [80]:
encode = preprocessing.OneHotEncoder()

# 2. Fit the encoder
encode.fit(nalltrailsonehot)

# 3. Transform to binary columns
onehotlabels = encode.transform(nalltrailsonehot).toarray()
onehotlabels.shape
onehotlabels


array([[0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.]])

In [81]:
newcols = ['Cat1a', 'Cat1b', 'Cat1c', 'Cat2a', 'Cat2b', 'Cat2c']
catvardf = pd.DataFrame(onehotlabels, columns = newcols)

catvardf

Cat1a  Cat1b  Cat1c  Cat2a  Cat2b  Cat2c
0       0.0    1.0    0.0    1.0    0.0    0.0
1       0.0    0.0    1.0    0.0    1.0    0.0
2       0.0    0.0    1.0    1.0    0.0    0.0
3       0.0    0.0    1.0    1.0    0.0    0.0
4       0.0    1.0    0.0    1.0    0.0    0.0
5       0.0    1.0    0.0    1.0    0.0    0.0
6       1.0    0.0    0.0    0.0    1.0    0.0
7       0.0    0.0    1.0    1.0    0.0    0.0
8       0.0    1.0    0.0    1.0    0.0    0.0
9       1.0    0.0    0.0    1.0    0.0    0.0
10      0.0    0.0    1.0    1.0    0.0    0.0
11      0.0    0.0    1.0    1.0    0.0    0.0
12      0.0    1.0    0.0    1.0    0.0    0.0
13      0.0    0.0    1.0    0.0    1.0    0.0
14      0.0    0.0    1.0    1.0    0.0    0.0
15      0.0    0.0    1.0    1.0    0.0    0.0
16      1.0    0.0    0.0    1.0    0.0    0.0
17      0.0    0.0    1.0    0.0    1.0    0.0
18      0.0    1.0    0.0    1.0    0.0    0.0
19      0.0    0.0    1.0    0.0    1.0    0.0
20      0.0    1.0    0.0    1.0    0.0    0.0
21      0.0    1.0    0.0    1.0    0.0    0.0
22      0.0    0.0    1.0    1.0    0.0    0.0
23      0.0    0.0    1.0    1.0    0.0    0.0
24      1.0    0.0    0.0    0.0    1.0    0.0
25      0.0    0.0    1.0    1.0    0.0    0.0
26      0.0    0.0    1.0    0.0    1.0    0.0
27      0.0    0.0    1.0    1.0    0.0    0.0
28      0.0    0.0    1.0    1.0    0.0    0.0
29      0.0    0.0    1.0    1.0    0.0    0.0
...     ...    ...    ...    ...    ...    ...
2179    1.0    0.0    0.0    0.0    1.0    0.0
2180    1.0    0.0    0.0    0.0    1.0    0.0
2181    0.0    0.0    1.0    1.0    0.0    0.0
2182    0.0    1.0    0.0    1.0    0.0    0.0
2183    0.0    1.0    0.0    0.0    1.0    0.0
2184    0.0    0.0    1.0    0.0    0.0    1.0
2185    1.0    0.0    0.0    1.0    0.0    0.0
2186    1.0    0.0    0.0    1.0    0.0    0.0
2187    1.0    0.0    0.0    0.0    1.0    0.0
2188    0.0    0.0    1.0    1.0    0.0    0.0
2189    1.0    0.0    0.0    1.0    0.0    0.0
2190    0.0    1.0    0.0    1.0    0.0    0.0
2191    0.0    1.0    0.0    1.0    0.0    0.0
2192    1.0    0.0    0.0    1.0    0.0    0.0
2193    1.0    0.0    0.0    0.0    0.0    1.0
2194    1.0    0.0    0.0    1.0    0.0    0.0
2195    0.0    1.0    0.0    0.0    1.0    0.0
2196    0.0    0.0    1.0    0.0    1.0    0.0
2197    1.0    0.0    0.0    1.0    0.0    0.0
2198    1.0    0.0    0.0    0.0    1.0    0.0
2199    1.0    0.0    0.0    0.0    1.0    0.0
2200    1.0    0.0    0.0    0.0    1.0    0.0
2201    1.0    0.0    0.0    0.0    1.0    0.0
2202    0.0    0.0    1.0    0.0    1.0    0.0
2203    0.0    0.0    1.0    1.0    0.0    0.0
2204    1.0    0.0    0.0    1.0    0.0    0.0
2205    0.0    0.0    1.0    1.0    0.0    0.0
2206    0.0    1.0    0.0    0.0    1.0    0.0
2207    0.0    1.0    0.0    1.0    0.0    0.0
2208    1.0    0.0    0.0    1.0    0.0    0.0

[2209 rows x 6 columns]

In [96]:
other_trails = nalltrails.loc[:, ['Distance_Miles', 'Elevation_Feet']]

X = pd.concat((other_trails, catvardf), axis = 1)
X

Distance_Miles  Elevation_Feet  Cat1a  Cat1b  Cat1c  Cat2a  Cat2b  Cat2c
0                1.4             488    0.0    1.0    0.0    1.0    0.0    0.0
1                4.0            1118    0.0    0.0    1.0    0.0    1.0    0.0
2                3.4              95    0.0    0.0    1.0    1.0    0.0    0.0
3                3.1             597    0.0    0.0    1.0    1.0    0.0    0.0
4                2.1            1049    0.0    1.0    0.0    1.0    0.0    0.0
5                7.5            2247    0.0    1.0    0.0    1.0    0.0    0.0
6                4.5             374    1.0    0.0    0.0    0.0    1.0    0.0
7                1.6             301    0.0    0.0    1.0    1.0    0.0    0.0
8                5.3            1952    0.0    1.0    0.0    1.0    0.0    0.0
9                0.3              45    1.0    0.0    0.0    1.0    0.0    0.0
10               1.7             334    0.0    0.0    1.0    1.0    0.0    0.0
11               1.4             492    0.0    0.0    1.0    1.0    0.0    0.0
12               3.5            1167    0.0    1.0    0.0    1.0    0.0    0.0
13               1.6             429    0.0    0.0    1.0    0.0    1.0    0.0
14               4.4            1551    0.0    0.0    1.0    1.0    0.0    0.0
15               3.6            1391    0.0    0.0    1.0    1.0    0.0    0.0
16               1.3              65    1.0    0.0    0.0    1.0    0.0    0.0
17               5.4            1984    0.0    0.0    1.0    0.0    1.0    0.0
18              17.0            8021    0.0    1.0    0.0    1.0    0.0    0.0
19               2.9             974    0.0    0.0    1.0    0.0    1.0    0.0
20               9.1            3894    0.0    1.0    0.0    1.0    0.0    0.0
21               2.7            1131    0.0    1.0    0.0    1.0    0.0    0.0
22               1.8             265    0.0    0.0    1.0    1.0    0.0    0.0
23               1.2             347    0.0    0.0    1.0    1.0    0.0    0.0
24               1.8             170    1.0    0.0    0.0    0.0    1.0    0.0
25               1.7             731    0.0    0.0    1.0    1.0    0.0    0.0
26               3.3            1512    0.0    0.0    1.0    0.0    1.0    0.0
27               1.3             449    0.0    0.0    1.0    1.0    0.0    0.0
28               7.5             977    0.0    0.0    1.0    1.0    0.0    0.0
29               1.8             475    0.0    0.0    1.0    1.0    0.0    0.0
...              ...             ...    ...    ...    ...    ...    ...    ...
2179             1.4             160    1.0    0.0    0.0    0.0    1.0    0.0
2180             1.4              72    1.0    0.0    0.0    0.0    1.0    0.0
2181             1.7             324    0.0    0.0    1.0    1.0    0.0    0.0
2182            10.7            2188    0.0    1.0    0.0    1.0    0.0    0.0
2183             8.8            2247    0.0    1.0    0.0    0.0    1.0    0.0
2184            13.3            4081    0.0    0.0    1.0    0.0    0.0    1.0
2185             2.6             272    1.0    0.0    0.0    1.0    0.0    0.0
2186             3.1             311    1.0    0.0    0.0    1.0    0.0    0.0
2187             3.2             187    1.0    0.0    0.0    0.0    1.0    0.0
2188             6.3            1689    0.0    0.0    1.0    1.0    0.0    0.0
2189             0.6             144    1.0    0.0    0.0    1.0    0.0    0.0
2190             7.8            1509    0.0    1.0    0.0    1.0    0.0    0.0
2191            27.5            6341    0.0    1.0    0.0    1.0    0.0    0.0
2192             0.5               9    1.0    0.0    0.0    1.0    0.0    0.0
2193             2.7             728    1.0    0.0    0.0    0.0    0.0    1.0
2194             0.6              13    1.0    0.0    0.0    1.0    0.0    0.0
2195             9.1            3848    0.0    1.0    0.0    0.0    1.0    0.0
2196             2.0             469    0.0    0.0    1.0    0.0    1.0    0.0
2197             2.2             114    1.0    0.0    0.

In [97]:
from sklearn.covariance import EllipticEnvelope
outlier_frac = 0.02

ell = EllipticEnvelope(contamination = outlier_frac)
ell.fit(X)

C:\Users\Jordan\Anaconda3\lib\site-packages\sklearn\covariance\robust_covariance.py:646: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "


EllipticEnvelope(assume_centered=False, contamination=0.02, random_state=None,
         store_precision=True, support_fraction=None)

In [98]:
#Checking for the number of outliers

pred = ell.predict(X)
print(sum(pred == -1) ) # Outlier points are predicted as -1
stats.itemfreq(pred)



45


C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  """


array([[  -1,   45],
       [   1, 2164]], dtype=int64)

In [99]:
keep = pred == 1

Xkeep = X[keep]

print(Xkeep.shape)
Xkeep.head()

(2164, 8)


Distance_Miles  Elevation_Feet  Cat1a  Cat1b  Cat1c  Cat2a  Cat2b  Cat2c
0             1.4             488    0.0    1.0    0.0    1.0    0.0    0.0
1             4.0            1118    0.0    0.0    1.0    0.0    1.0    0.0
2             3.4              95    0.0    0.0    1.0    1.0    0.0    0.0
3             3.1             597    0.0    0.0    1.0    1.0    0.0    0.0
4             2.1            1049    0.0    1.0    0.0    1.0    0.0    0.0

In [100]:
scaler = StandardScaler()

ready_to_clusterstd = scaler.fit_transform(Xkeep)

C:\Users\Jordan\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Jordan\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [101]:
from sklearn.decomposition import PCA

pca = PCA(0.90)
pca.fit(ready_to_clusterstd)

pca.n_components_

4

In [102]:
pca_components = pca.transform(ready_to_clusterstd)
pca_components.shape

(2164, 4)

In [103]:
Xkeep["index"] = Xkeep.index
Xkeep2 = Xkeep.reset_index()
Xkeep2.head()

C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


level_0  Distance_Miles  Elevation_Feet  Cat1a  Cat1b  Cat1c  Cat2a  Cat2b  \
0        0             1.4             488    0.0    1.0    0.0    1.0    0.0   
1        1             4.0            1118    0.0    0.0    1.0    0.0    1.0   
2        2             3.4              95    0.0    0.0    1.0    1.0    0.0   
3        3             3.1             597    0.0    0.0    1.0    1.0    0.0   
4        4             2.1            1049    0.0    1.0    0.0    1.0    0.0   

   Cat2c  index  
0    0.0      0  
1    0.0      1  
2    0.0      2  
3    0.0      3  
4    0.0      4

In [104]:
cols = []
for i in range (1, 5):
    cols.append("PC" + str(i))

print(cols)

PCdf = pd.DataFrame(pca_components, columns = cols, index  =  Xkeep.index)
PCdf.head()

['PC1', 'PC2', 'PC3', 'PC4']


PC1       PC2       PC3       PC4
0  0.136529  1.629438 -0.068469 -0.981418
1  0.550061 -1.915989  0.782815  0.034991
2 -0.901937  0.338701  1.881356 -0.012276
3 -0.734393  0.392570  1.883690 -0.068989
4  0.445905  1.739028 -0.063931 -1.021127

In [105]:

labels = []
for i in range(5,13):
    kmeans = KMeans(n_clusters= i)
    kmeans = kmeans.fit(PCdf)
    labelPCdf = kmeans.labels_
    labels.append(labelPCdf)
    centroids = kmeans.cluster_centers_
    centroids[:, 0]
    print(stats.itemfreq(labelPCdf))
   


C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and 

[[  0 750]
 [  1 448]
 [  2  77]
 [  3 509]
 [  4 380]]
[[  0 319]
 [  1 509]
 [  2 435]
 [  3  77]
 [  4 376]
 [  5 448]]
[[  0 319]
 [  1 448]
 [  2 163]
 [  3 508]
 [  4 433]
 [  5 216]
 [  6  77]]
[[  0 448]
 [  1 216]
 [  2 508]
 [  3 433]
 [  4 319]
 [  5  33]
 [  6  44]
 [  7 163]]
[[  0 102]
 [  1 508]
 [  2 209]
 [  3 448]
 [  4 319]
 [  5  44]
 [  6 163]
 [  7  33]
 [  8 338]]
[[  0 448]
 [  1 147]
 [  2 508]
 [  3  33]
 [  4 319]
 [  5 102]
 [  6 163]
 [  7  44]
 [  8  62]
 [  9 338]]
[[  0 338]
 [  1 508]
 [  2 147]
 [  3 448]
 [  4 319]
 [  5  33]
 [  6  86]
 [  7  44]
 [  8  62]
 [  9 102]
 [ 10  77]]
[[  0 338]
 [  1  78]
 [  2 508]
 [  3 319]
 [  4 448]
 [  5  62]
 [  6  33]
 [  7  24]
 [  8  85]
 [  9 102]
 [ 10 147]
 [ 11  20]]


C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Jordan\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  # Remove the CWD from sys.path while we load stuff.


In [106]:
#Let's go with 6 cluster groups
whole_cluster = labels[1]
whole_cluster.view()

PCdf["Cluster_number_whole"] = whole_cluster
print(PCdf.head())
PCdf["Cluster_number_whole"].value_counts()

        PC1       PC2       PC3       PC4  Cluster_number_whole
0  0.136529  1.629438 -0.068469 -0.981418                     1
1  0.550061 -1.915989  0.782815  0.034991                     2
2 -0.901937  0.338701  1.881356 -0.012276                     5
3 -0.734393  0.392570  1.883690 -0.068989                     5
4  0.445905  1.739028 -0.063931 -1.021127                     4


1    509
5    448
2    435
4    376
0    319
3     77
Name: Cluster_number_whole, dtype: int64

In [110]:
completetrails = pd.concat([alltrails, PCdf], axis = 1)
completetrails.head()
completetrails.shape

(2209, 16)

In [111]:
completetrails.to_csv("NHMaineCompleteClusteredTrails.csv")